#!/bin/sh

# PSQL
touch $HOME/.psqlrc.local

# Vundle
if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi
vim -u $HOME/.vimrc.bundles +PluginInstall +PluginClean! +qa

# OH MY ZSHELL
if [ ! -e $HOME/.oh-my-zsh ]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
fi

